### ISSUE TITLE
ES's interest in Calculate package?

### ISSUE THREAD

**Issue by reagle** [STealthy-and-haSTy/EnhancedSnippets#5]
This morning when I update/overwrite installed packages I noted it took longer than usual and I see these in the log. I also believe [Calculate](https://github.com/colinta/SublimeCalculate) was updated.

```
ignored packages updated to: ["Calculate", "Vintage"]
unloading python 3.3 plugin Calculate.calculate
EnhancedSnippets: settings change on ignored_packages detected
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
EnhancedSnippets: discarding all snippets in package 'Calculate'
EnhancedSnippets: discarding all loaded enhancements from package 'Calculate'
ignored packages updated to: ["Vintage"]
EnhancedSnippets: settings change on ignored_packages detected
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading python 3.3 plugin Calculate.calculate
EnhancedSnippets: scanning for enhanced snippets in package 'Calculate'
EnhancedSnippets: discarding all loaded enhancements from package 'Calculate'
EnhancedSnippets: rescanning enhancements in package 'Calculate'
reloading settings Packages/User/Preferences.sublime-settings
```

Any idea what's going on there? Does ES scan all packages for snippets?

**Comment by OdatNurd** [comment]
It does indeed; the main goal is to have enhanced snippets behave the same as a "native" snippet, as much as is possible. This means that any package can include such a snippet (or a plugin that adds extra variables).

When packages get added to `ignored_packages`, Sublime unloads the resources from them, so ES catches that and discards its cache of snippets and variables that are sourced from that package.

Similarly, when a package comes out of `ignored_packages`, it gets scanned to see if it's contributing anything, and the files load the same as they would at startup.

When PC updates a package (or installs one) it puts it into `ignored_packages` because Windows locks files that are in use and it needs the files to be released; thus for any package that updates you will see log messages about it first discarding and then rescanning. 

Those messages are more verbose than they need to be at the moment due to the Alpha state; the ultimate goal is to have the messaging be minimal but have a `debug` flag that can be enabled to make them more verbose.

That said, the scan for snippets and variables should not take much time since it's just doing `sublime.find_resources('*.enhanced-sublime-snippet')` and `sublime.find_resources('.enhanced-snippets')` which are core level API's that pre-filter the already known resource list.

**Comment by reagle** [comment]
Okay, thank you. Closing. (BTW: you two redundant/garbled paragraphs at the end.)
