### ISSUE TITLE
repo slows "update all packages"

### ISSUE THREAD

**Issue by reagle** [STealthy-and-haSTy/EnhancedSnippets#7]
When I ask ST4 to update/overwrite all plugins, having the ES repo installed significantly increases the time to complete. Typically, I'll see the cursor swipe back and forth for a second. With <https://raw.githubusercontent.com/STealthy-and-haSTy/SublimePackages/master/unreleased-packages.json> installed, it takes 5--10 seconds to load the repos for a search, install, or update_all.

To confirm, I removed ST and its repo, quit, and ran update/overall-all; and then reinstalled and see the same lag.

**Comment by reagle** [comment]
more accurate estimate: 12 seconds

**Comment by OdatNurd** [comment]
So, this is an issue related to having the `unreleased-packages.json` file in the repository list?

If so, that's more of a package control issue, since it's the thing hat scans the list of packages and it either doesn't cache, or is running into rate limiter problems.

If so, the only fix for this is to promote this package to an officially released package instead. We can likely work towards an MVP alpha worthy of being in that repo in the next couple of weeks or so.

I'll have to double check the options for making a package a prerelease in PC.

**Comment by OdatNurd** [comment]
Just to provide an update on this, work is currently still in progress to create an initial Alpha version of the package that can be released to PC in the released packages channel, which would allow you to install it without having to have the additional repo file added.

This will require adding the following to your Package Control settings (or add the package if the setting is already there:

```json
"install_prereleases": ["EnhancedSnippets"],
```

As of last Monday, this is also required when installing via the method of including the additional package repository file, in preparation for this move.

Since the release of this to the official channel as a prerelease will resolve this issue, and there is nothing other than this that I can do to resolve the original problem (due to it being a PC problem directly), I am going to close this issue for now.
